spring:
  application:
    name: discovery-server
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 10000
    responseCacheAutoExpirationInSeconds: 0
  instance:
    preferIpAddress: true



